# ============================================================
# OceanOSSE Example Configuration: NEMO eORCA1 ERA5v1
# ============================================================
# To run:
#   OceanOSSE run examples/example_config.toml
#   OceanOSSE run examples/example_config.toml --dry-run
# ============================================================

# ========================== Inputs ==========================
[inputs]
data_dir = "/path/to/nemo/output"
format = "netcdf"

[inputs.dimensions]
time = "time_counter"
lev  = "deptht"
j    = "y"
i    = "x"

[inputs.coordinates]
time = "time_counter"
depth = "deptht"
lon = "nav_lon"
lat = "nav_lat"

[inputs.variables.thetao_con]
path = "/dssgfs01/scratch/npd/simulations/eORCA1_ERA5_v1/eORCA1_ERA5_1m_grid_T_202312-202312.nc"
open_kwargs = { engine = "netcdf4" }

[inputs.variables.so_abs]
path = "/dssgfs01/scratch/npd/simulations/eORCA1_ERA5_v1/eORCA1_ERA5_1m_grid_T_202312-202312.nc"
open_kwargs = { engine = "netcdf4" }

# ========================== Sampling ==========================
[sampling]
name = "test"

[[sampling.error_kernels]]
name = "test"
kwargs = { sigma = 1.0 }

# ========================== Regridding ==========================
[regridding]
name = "test"
kwargs = { method = "nearest_s2d" }

# ========================== Outputs ==========================
[outputs]
format = "netcdf"
output_dir = "/dssgfs01/working/otooth/Software/OceanOSSE/OceanOSSE"
output_name = "OceanOSSE_TEST"
date_format = "M"
chunks = { time_counter = 12 }
writer_kwargs = { unlimited_dims = "time_counter", mode = "w" }
