name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run OceanOSSE Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Install dependencies using Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.67.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}

      - name: 🧪 Run OceanOSSE Unit Tests
        run: pixi run tests
